remote_theme: avikam03/jekyll-gitbook

syntax_highlighter_style: molokai

github_username: avikam03
twitter_username: avikam03

toc:
  enabled:       true
  enabled_index: true
  h_min:         1
  h_max:         6

kramdown:
  toc_levels: 1..6
